start-enketo: simplify config generation
getodk/central pull request #332
Opened 2022-10-07 07:40 UTC by alxndrsn

The original code looks like it's doing something clever (e.g. protecting secrets from leaking into the `pm2` process?), but I can't work out what it is...

2022-10-18 17:13 UTC, lognaturel commented
@issa-tseng doesn't think there was a reason for the original structure.

2023-01-06 20:59 UTC, matthew-white commented
@yanokwa, do you have time to take a look at this? Also happy to pick a different reviewer if that'd be better.

2023-01-11 17:32 UTC, yanokwa approved these changes
LGTM. I confirmed that envsubst does the right substitution (at least on my Mac). I also confirmed that variables with spaces work.

2023-01-11 17:42 UTC, yanokwa requested changes
I think the reason for `bash -c` is probably to guarantee that we don't clobber any existing env variables (because the names we use are generic) or leave those variables behind for some rogue process to exfiltrate.

We should leave the code as-is, but add a comment explaining why we have this.

2023-01-12 14:56 UTC, alxndrsn commented
> guarantee that we don't clobber any existing env variables (because the names we use are generic) or leave those variables behind for some rogue process to exfiltrate.

I think that is already covered... E.g.

```bash
KEEP_ME=1
echo "KEEP_ME (original):    $KEEP_ME"
echo "DONT_LEAK:             $DONT_LEAK"

echo '---'

KEEP_ME=2 \
DONT_LEAK=X \
envsubst '$KEEP_ME$DONT_LEAK' <<<'KEEP_ME (substituted): $KEEP_ME
DONT_LEAK:             $DONT_LEAK'

echo '---'

echo "KEEP_ME (final):       $KEEP_ME"
echo "DONT_LEAK:             $DONT_LEAK"
```

will print:

```shell
KEEP_ME (original):    1
DONT_LEAK:             
---
KEEP_ME (substituted): 2
DONT_LEAK:             X
---
KEEP_ME (final):       1
DONT_LEAK:             
```

2023-01-12 17:57 UTC, yanokwa commented
I stand corrected. 

I propose we apply this change to the following and merge at once.
files/service/scripts/start-odk.sh
files/nginx/odk-setup.sh

2023-02-23 00:26 UTC, lognaturel commented
@yanokwa @alxndrsn the todo here is to apply the change more broadly?

2023-02-23 08:01 UTC, alxndrsn commented on .circleci/config.yml
> +      - run: cat <(git grep -El '^#!.*sh\b') <(git ls-files | grep -E '.sh$') | sort -u | grep -v '/wait-for-it.sh$' | xargs shellcheck --exclude=SC2016
It might be nice to have a `scripts` directory for storing things like this.  This would also make running the command locally more convenient.

2023-02-23 08:02 UTC, alxndrsn commented
@lognaturel @yanokwa I've applied the change to the requested files.

2023-03-01 06:38 UTC, lognaturel approved these changes

2023-03-01 06:39 UTC, lognaturel commented
Verified on dev server. This will make adding more env vars a bit more palatable.

2023-03-01 06:39 UTC, merged