Optimise central backend (service) dockerfile, use slim node
getodk/central pull request #549
Opened 2023-11-27 04:35 UTC by spwoodcock

## Includes

- Built using `node:18-slim` instead of `node:18.7`.
  - I assumed we probably want patch versions of node that shouldn't be breaking.
  - Is the assumption correct, or should I change back to pinned `18.7`?
- Merged RUN directives where possible
  - This was less significant than I thought, maybe 50 - 100 MB saving.
  - The dockerfile was missing a cleanup of the apt list here too: https://github.com/getodk/central/blob/774b491961578bd6e03ceaa6cf8032dd27b828a7/service.dockerfile#L21-L22
- Absolute paths for WORKDIR (as per dockerfile-utils linting).
- Add HEALTHCHECK. This is useful for docker-compose setups. It's ignored in Kubernetes.
- Remove deprecated EXPOSE command and replace with LABELs.

## Discussion

I image the reason for not using a slim image originally is because they don't have git installed for the
`git describe --tags --dirty` command. Solved with multi-stage.

This PR was originally discussed as part of #519.
Reducing the space required to build images may be useful on systems with very limited space.
However, the gains that can be made are rather small considering >1 GB of cached images shouldn't really be a problem for most.

There have been discussions around providing pre-built images and an open PR to facilitate this, so this discussion will be moot if that is merged.

There is always a tradeoff between cache image bloat and dockerfile readability.
However, in this example I personally think the original is much more readable:

```dockerfile
FROM node:${node_version}-slim as intermediate
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
    && rm -rf /var/lib/apt/lists/*
COPY . .
RUN mkdir /tmp/sentry-versions
RUN git describe --tags --dirty > /tmp/sentry-versions/central
WORKDIR /server
RUN git describe --tags --dirty > /tmp/sentry-versions/server
WORKDIR /client
RUN git describe --tags --dirty > /tmp/sentry-versions/client
```

compared to less readable & not best practice of `cd` in dockerfiles (for little gain):

```dockerfile
FROM node:${node_version}-slim as intermediate
COPY . .
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /tmp/sentry-versions \
    && git describe --tags --dirty > /tmp/sentry-versions/central \
    && cd server && git describe --tags --dirty > /tmp/sentry-versions/server \
    && cd ../client && git describe --tags --dirty > /tmp/sentry-versions/client
```

> Note that this is not the final build stage, so the discussion is about image cache bloat,
> not intermediate image layer size.

2023-11-27 05:21 UTC, lognaturel commented
Thanks for opening! I'm not entirely sure when we'll be able to take a focused look at this and #546, it may be after the current release goes out.

> Built using node:18-slim instead of node:18.17

We do want to pin the minor version because there are more likely to be accidental breaking changes between minor versions and usually they're not critical to apply. We update minor versions when we release. We do want to leave the patch version floating so that a rebuild can get the latest patches (so we don't want e.g. node:18.17.1).

2023-12-06 23:23 UTC, lognaturel requested changes
Couple of quick things to update. Other than that, this looks ready to me. Current plan is to merge it right after the release ~Dec 15. We may also end up publishing images in which case it's less important but let's still get it in first.

2023-12-06 23:23 UTC, lognaturel commented on service.dockerfile
> +HEALTHCHECK --start-period=10s --interval=5s --retries=10 \
Let's separate out the healthcheck concern. An interval of 5s sounds aggressive to me but maybe it doesn't matter because it's not resource-intensive. It does seem like a bit of an oversight not to have any explicit simple healthcheck but if we do add one that just checks if there's a response at the port maybe it could go outside (e.g. in the Docker Compose config). We've also considered adding a healthcheck endpoint in backend. Let's sort it out in an issue! For deployments we tend to use entirely separate services for health monitoring.

2023-12-07 04:57 UTC, spwoodcock commented on service.dockerfile
> +      org.getodk.central.maintainer="admin@hotosm.org" \
Oops! Was clearly in a rush

2023-12-07 04:59 UTC, spwoodcock commented on service.dockerfile
> +HEALTHCHECK --start-period=10s --interval=5s --retries=10 \
Good point - it's easier for the user to configure via docker compose instead of here 👍

2023-12-08 21:09 UTC, lognaturel commented
Before:
> docker inspect -f "{{ .Size }}" central-service | numfmt --to=si
1.3G

After:
> docker inspect -f "{{ .Size }}" central-service | numfmt --to=si
374M

Secrets goes from 1.1G to 201M and nginx only gets a change to the intermediate stage but that's still nice.

2023-12-08 21:53 UTC, lognaturel commented
> I image the reason for not using a slim image originally is because they don't have git installed

https://github.com/getodk/central/pull/249#issuecomment-949986638 has some context. The past attempt was to move to alpine. There used to be a lua script in the nginx container that didn't work well with that but it's been removed. We have historically been somewhat more concerned about download size than local storage size. The change to `20.10-slim` will **add** ~[60MB](https://hub.docker.com/layers/library/node/20.10-slim/images/sha256-18aacc7993a16f1d766c21e3bff922e830bcdc7b549bbb789ceb7374a6138480?context=explore) to the overall download because Enketo will pull the `20.10` image. I think that's ok and we can align Enketo in the next release.

This discussion made me realize we should use an alpine image for postgres14 so I added that change.

2023-12-08 23:15 UTC, lognaturel commented on service.dockerfile
> +EXPOSE 8383
The original PR description states that `EXPOSE` is deprecated. I see no evidence of this: https://docs.docker.com/engine/reference/builder/#expose

2023-12-08 23:17 UTC, lognaturel commented on service.dockerfile
> +LABEL org.opencontainers.image.title="ODK Central backend" \
The only accepted standard for labels that I know of is [this one](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys). GHCR does recognize a few of them: https://docs.github.com/en/enterprise-server@3.8/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images

2023-12-08 23:21 UTC, lognaturel commented
@yanokwa can you please do a sanity check? I'm satisfied that:
- it's a clean update
- there's user value
- it doesn't introduce anything non-standard
- it applies the improvement consistently and as broadly as it can

2023-12-09 00:27 UTC, yanokwa commented on service.dockerfile
> +LABEL org.opencontainers.image.title="ODK Central backend" \
My bias is to only include `org.opencontainers.image.source`. It's what GHCR supports and so is likely to be useful. It's ambiguous what to put there, which I like. Anything else seems to be of minor value so I'd rather not commit to it.

2023-12-09 00:30 UTC, yanokwa commented on service.dockerfile
> +EXPOSE 8383
Expose is for documenting the port the builder of the image intends to publish. It does actually publishing it, so maybe that's the confusion? Either way, agreed that we can leave this.

2023-12-09 00:31 UTC, yanokwa approved these changes

2023-12-09 00:33 UTC, merged

2023-12-09 06:41 UTC, spwoodcock commented on service.dockerfile
> +EXPOSE 8383
Sorry, my mistake!

I always leave out EXPOSE and prefer a LABEL, as expose doesn't actually do anything to the image.

Using a label allows a user to `docker inspect` to easily know which port they need to bind.

2023-12-09 23:28 UTC, yanokwa commented on service.dockerfile
> +EXPOSE 8383
It's not a bad idea. Is it used anywhere else? Or documented somewhere as a best practice?

2023-12-10 08:43 UTC, spwoodcock commented on service.dockerfile
> +EXPOSE 8383
Not as far as I can see!

For a long time LABEL had no standard set, so it's good to see opencontainers create one.

I added the port label from my own frustrations with using other images.
If the author doesn't have a label, then I had to hunt down either the dockerfile (if they use EXPOSE) or the application config to find the port.

**Updates in my knowledge**

- LABEL and ENV no longer require multiline definition. It's more readable to use individual lines. 

- EXPOSE is now used by both docker and podman `-P` flag, to map all exposed ports to random ports on the host (does not seem useful to me, but maybe to some?).

2023-12-11 18:19 UTC, lognaturel commented on service.dockerfile
> +EXPOSE 8383
Thanks again for getting these improvements in!

When doing `docker inspect`, doesn't `Config/ExposedPorts` show the ports that were specified with `EXPOSE`?

2023-12-11 20:49 UTC, spwoodcock commented on service.dockerfile
> +EXPOSE 8383
You are correct!
That's an oversight from me.

I thought that `EXPOSE` was a useless command for years.
By the looks of it, it is actually a nice way to document via the metadata.

2023-12-11 21:37 UTC, lognaturel commented on service.dockerfile
> +EXPOSE 8383
I think so! And downstream tools could use it programmatically, hopefully to do more useful things than random port binding. 😄 🤷🏻‍♀️ It's also very possible that `Config/ExposedPorts` is relatively new. There's a lot to learn and keep track of!

2024-01-26 23:37 UTC, lognaturel commented
I just noticed that the Enketo image we produce automatically for GHCR gets some labels. I assume it's the Github action we use that does this:

```
  "labels": {
    "org.opencontainers.image.url": "https://github.com/enketo/enketo",
    "org.opencontainers.image.licenses": "Apache-2.0",
    "org.opencontainers.image.title": "enketo",
    "org.opencontainers.image.revision": "2f27f07b9d72eb27fb8576570501682b2f3ca5d2",
    "org.opencontainers.image.created": "2024-01-26T20:11:10.683Z",
    "org.opencontainers.image.version": "7.1.0",
    "org.opencontainers.image.description": "Enketo web forms monorepo",
    "org.opencontainers.image.source": "https://github.com/enketo/enketo"
  }
```

looks like `version` uses a tag if it exists or falls back to the branch name. I have not yet investigated whether this or what's specified in a Dockerfile takes precedence.

2024-01-31 11:53 UTC, spwoodcock commented
Interesting - the part of the workflow that does it is here: https://github.com/enketo/enketo/blob/2f27f07b9d72eb27fb8576570501682b2f3ca5d2/.github/workflows/ghcr.yml#L50

I use docker/build-push-action a lot, but only ever set the tags from docker/metadata-action, not the labels 🤦

2024-02-01 01:26 UTC, lognaturel commented
Looks like a good approach, we can look at adding that to https://github.com/getodk/central/pull/546