Add workflow to publish nginx and service images to GHCR
getodk/central pull request #676
Opened 2024-06-24 21:46 UTC by lognaturel

Based on #249, https://github.com/getodk/central/pull/546

#### What has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Does this change require updates to documentation? If so, please file an issue [here](https://github.com/getodk/docs/issues/new) and include the link below.

#### Before submitting this PR, please make sure you have:

- [ ] branched off and targeted the `next` branch OR only changed documentation/infrastructure (`master` is stable and used in production)
- [ ] verified that any code or assets from external sources are properly credited in comments or that everything is internally sourced

2024-06-25 03:46 UTC, spwoodcock commented
What do you think about building the images multi-arch?

Similar to pyxform-http:

```yaml
            # Setup QEMU emulator to build multi-arch images
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            # Configure Buildx for Docker build
            # https://github.com/docker/setup-buildx-action
            - name: Set up Buildx
              uses: docker/setup-buildx-action@v3

            # Build and push Docker image with Buildx
            # https://github.com/docker/build-push-action
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: 'linux/amd64,linux/arm64'
```

The main things are the two additional actions above the build + the specified `platforms` during the build.

2024-06-25 03:49 UTC, lognaturel commented
Oh yes, I meant to add that to the todo! We can do that here. 👍

2024-06-25 03:51 UTC, spwoodcock commented
Although this does run on every push, so building multi-arch will add to the build time and might not make sense. 

Do you think it might be good to build on release instead, or perhaps in addition?

The docker/metadata action will handle correct image tagging for releases.

2024-06-25 19:18 UTC, lognaturel commented
> this does run on every push

That I do have in my todo list to address! I'm just leaving it like that until all the other issues are addressed. I can add multiarch at that same time since you've told me exactly how. 🎉

2024-06-26 16:04 UTC, lognaturel commented on docker-compose.yml
> +      - ./files/nginx/common-headers.conf:/usr/share/odk/nginx/common-headers.conf
@yanokwa we do want users to be able to customize `redirector.conf` and `common-headers.conf`, right?

2024-06-26 17:04 UTC, yanokwa commented on docker-compose.yml
> +      - ./files/nginx/common-headers.conf:/usr/share/odk/nginx/common-headers.conf
No customization on either.

2024-06-26 17:09 UTC, yanokwa requested changes

2024-06-26 17:09 UTC, yanokwa commented on files/nginx/setup-odk.sh
> -cp /usr/share/odk/nginx/redirector.conf /etc/nginx/conf.d/redirector.conf
You'll likely need to add this back. It was there because if you go from upstream to letsencrypt, the file at `/etc/nginx/conf.d/redirector.conf` gets overwritten and you need a fresh template.

2024-06-26 17:09 UTC, yanokwa commented on files/nginx/setup-odk.sh
> +if [[ $OIDC_ENABLED != 'true' ]] && [[ $OIDC_ENABLED != 'false' ]]; then
This is more robust, but we don't do any other such checking elsewhere. I'd bias toward if true, then it's enabled. If it's anything else, it's not enabled.

2024-06-26 18:27 UTC, lognaturel commented on docker-compose.yml
> +      - ./files/nginx/common-headers.conf:/usr/share/odk/nginx/common-headers.conf
Got it. I've moved this back to a copy in the Dockerfile, then. That means those files will be copied at build time so will be static in the image.

2024-06-26 18:28 UTC, lognaturel commented on files/nginx/setup-odk.sh
> -cp /usr/share/odk/nginx/redirector.conf /etc/nginx/conf.d/redirector.conf
Ahh, yes. I've added a comment.

2024-06-26 20:52 UTC, yanokwa reviewed
Before merging, verify that toggling between self-sign, upstream, and letsencrypt works

2024-06-26 22:04 UTC, lognaturel commented
- Started with customssl, confirmed working
- Switched to selfsign, confirm Firefox gives self-signed security error, confirm `/etc/selfsign/live/local/` has fullchain and privkey, confirmed let's encrypt redirect is gone from redirector.conf
- Switched back to customssl, confirmed working
- Switched to letsencrypt, confirmed working; `/etc/nginx/conf.d/redirector.conf` has challenge reply, Firefox shows Let's Encrypt cert
- Switched to upstream, `redirector.conf` is gone, I see `X-Forwarded-Proto https` in nginx conf
- Switched back to customssl, confirmed working

All of this is near instant: modify .env, `docker compose up -d`, that's it.

2024-06-26 22:23 UTC, yanokwa approved these changes

2024-06-26 22:39 UTC, lognaturel commented
Thanks for the review @spwoodcock and @yanokwa! Let’s merge now and then file issues as we see improvements to make.

2024-06-26 22:41 UTC, merged